title: Rugplay Logger
description: A TypeScript WebSocket client for logging and exporting Rugplay trading events
theme: just-the-docs

url: https://your-username.github.io/rugplay-logger

aux_links:
  GitHub Repository: https://github.com/your-username/rugplay-logger
  
# Search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation structure
nav_sort: case_insensitive

# Footer content
footer_content: "Copyright &copy; 2024 Rugplay Logger. Distributed under the <a href=\"https://github.com/wbrous/rugplay-ws/blob/main/LICENSE\">GNU License</a>."

# Color scheme
color_scheme: nil

# Plugins
plugins:
  - jekyll-seo-tag
