title: RugplayWS
description: A TypeScript WebSocket client for logging and exporting Rugplay trading events
theme: just-the-docs

url: https://rugplayws.gir0fa.com

aux_links:
  GitHub Repo: https://github.com/wbrous/rugplay-ws
  
# Search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation structure
nav_sort: case_insensitive

# Footer content
footer_content: "Copyright &copy; 2025 Rugplay Logger. Distributed under the <a href=\"https://github.com/wbrous/rugplay-ws/blob/main/LICENSE\">GNU License</a>."

# Plugins
plugins:
  - jekyll-seo-tag
